name: sakay_v2
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  parse_server_sdk_flutter: ^3.1.3
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  font_awesome_flutter: ^10.2.1
  google_fonts: 3.0.1
  cupertino_icons: ^1.0.2
  flutter_gen: ^4.3.0
  shared_preferences: ^2.0.15
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.2.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  image_path: "assets/images/logo/1024.png"

flutter_native_splash:
  color: "#9EB86D"
  image: assets/images/splash/play_store_512.png
  android_12:
    image: assets/images/splash/play_store_512.png
    icon_background_color: "#9EB86D"
  android_gravity: center
  fullscreen: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/
